name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # - name: Install dependencies
      #   run: npm install

      # - name: Build
      #   run: npm start

      - name: Deploy to Digital Ocean
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_SECRET_KEY: ${{ secrets.CLOUDINARY_SECRET_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "Known Hosts now::: ${{ secrets.DO_HOST }}"
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.HAPICHAT_SSH_KEY }}"
          echo "${{ secrets.HAPICHAT_SSH_KEY }}" | tr -d '\r' > do_key.pem
          chmod 600 do_key.pem
          ssh -i do_key.pem ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}
          rsync -avz -e "ssh -i do_key.pem" --exclude '.git/' --exclude 'node_modules/' ./ ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:~/mediaservice
          ssh -i do_key.pem ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} <<EOF
            cd /mediaservice
            echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
            echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
            echo "CLOUDINARY_SECRET_KEY=${{ secrets.CLOUDINARY_SECRET_KEY }}" >> .env
            npm install
            npm start
            EOF
          rm -f do_key.pem
